apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  defaultBackend:
    service:
      name: keyconverter-service
      port:
        number: 8080
  
      
