apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  rules:
  - http:
      paths:
      - path: /key
        pathType: Prefix
        backend:
          service:
           name: keyconverter-service
           port: 
            number: 8080
      - path: /demo
        pathType: Prefix
        backend:
          service:
           name: demo-service
           port:
            number: 8080
      
