apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyconverter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      cloud: armor
  template:
    metadata:
      labels:
        cloud: armor
    spec:
      containers:
      - name: key-converter
        image: europe-west3-docker.pkg.dev/test-standalone-project-1/poc-gke-lb/demo-gke-app:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: keyconverter-service
spec:
  type: ClusterIP
  selector:
    cloud: armor
  ports:
  - port: 8000 #My wish
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: gcr.io/google-samples/whereami:v1.2.6
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - port: 9000
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: https-ingress
spec:
  defaultBackend:
    service:
      name: demo-service
      port:
        number: 9000
  rules:
  - http:
      paths:
      - path: /armor
        pathType: ImplementationSpecific
        backend:
          service:
            name: keyconverter-service
            port:
              number: 8000
      